- src/main/java/sopt/org/homepage/entity/NotificationEntity.java
- src/main/java/sopt/org/homepage/exception/GlobalExceptionHandler.java
- src/main/java/sopt/org/homepage/notification/NotificationController.java
- src/main/java/sopt/org/homepage/notification/NotificationEntity.java
- src/main/java/sopt/org/homepage/notification/NotificationRepository.java
- src/main/java/sopt/org/homepage/notification/NotificationService.java
- src/main/java/sopt/org/homepage/notification/dto/GetNotificationListRequestDto.java
- src/main/java/sopt/org/homepage/notification/dto/GetNotificationListResponseDto.java
- src/main/java/sopt/org/homepage/notification/dto/RegisterNotificationRequestDto.java
- src/main/java/sopt/org/homepage/notification/dto/RegisterNotificationResponseDto.java
* 모집알림 기능 Spring 마이그레이션 작업
* /notification/register POST → 모집알림 등록
* /notification/list GET  → 모집알림 신청 목록 조회
* Swagger Docs /v2/api-docs
* SpringBoot Domain Package 코드 구조 및 컨벤션 확인
> [Feat]: Notification 모집알림 기능 v2 API 마이그레이션 작업

- src/main/java/sopt/org/homepage/aboutsopt/AboutSoptController.java
- src/main/java/sopt/org/homepage/aboutsopt/AboutSoptService.java
- src/main/java/sopt/org/homepage/aboutsopt/dto/AboutSoptResponseDto.java
- src/main/java/sopt/org/homepage/aboutsopt/dto/CoreValueResponseDto.java
- src/main/java/sopt/org/homepage/aboutsopt/dto/GetAboutSoptResponseDto.java
- src/main/java/sopt/org/homepage/aboutsopt/entity/AboutSoptEntity.java
- src/main/java/sopt/org/homepage/aboutsopt/entity/CoreValueEntity.java
- src/main/java/sopt/org/homepage/aboutsopt/repository/AboutSoptRepository.java
- src/main/java/sopt/org/homepage/exception/NotFoundException.java
- src/main/java/sopt/org/homepage/internal/playground/PlaygroundService.java
- src/main/java/sopt/org/homepage/project/ProjectService.java
- aboutsopt관련 조회 api 마이그레이션 작업
- /aboutsopt Get -사용자용 aboutsopt데이터 조회
- Swagger Docs /v2/api-docs
- aboutSopt API 실행 흐름 플로우
> [Feat]:aboutsopt 조회 기능 v2 API 마이그레이션 작업

- src/main/java/sopt/org/homepage/aws/s3/S3ServiceImpl.java
- src/main/java/sopt/org/homepage/main/dto/response/GetAboutPageResponseDto.java
- src/main/java/sopt/org/homepage/main/dto/response/GetMainPageResponseDto.java
- src/main/java/sopt/org/homepage/main/service/MainServiceImpl.java
* S3 파일 원본 링크 잘못된 경로로 저장되는 이슈 수정
* 메인 페이지 데이터 조회 시, 지원 일정도 조회되도록 작업
* About 페이지 데이터 조회 시, 지난 기수 활동 레코드 함께 조회 (기존 aboutSopt API)
* /v2/api-docs Swagger
> [Refac]: 어드민 프론트 QA 요청사항 반영

- src/main/java/sopt/org/homepage/aboutsopt/AboutSoptService.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
> [Fix]: AboutSoptService MainService 순환참조 오류 수정 & Crew API Token 환경 변수 추가

- .github/workflows/cd.production.yml
* 공홈 SpringBoot v2 서버 프로덕션 배포
* main 브랜치 머지 후, 메인 API  /v2/api-docs 스워거 확인
> [Feat]: 공홈 V2 서버 프로덕션 배포 작업

- .github/workflows/cd.develop.yml
- .github/workflows/cd.production.yml
- src/main/java/sopt/org/homepage/notification/NotificationController.java
- src/main/java/sopt/org/homepage/notification/NotificationService.java
* v2 서버 Dev 프론트 연동 QA
* 공홈 어드민
* 기존 공홈 API 리스트
> feat: v2 서버 최종 QA 및 프로덕션 배포

- src/main/java/sopt/org/homepage/aws/s3/S3ServiceImpl.java
> [Fix]: S3 FileKey 기반으로 이미지링크 저장시, SignedLink 대신 원본 URL 로 저장되도록 수정

- .github/workflows/cd.develop.yml
> deploy : 통합 dev 인스턴스 이전으로 인한 포트 변경

- .github/workflows/cd.develop.yml
> deploy : aws username 수정

- .github/workflows/cd.develop.yml
> deploy : key이름 변경

- .github/workflows/cd.develop.yml
> deploy : DEV 통합 인스턴스에 맞는 디렉토리 구조로 script 수정

- Dockerfile
- src/main/java/sopt/org/homepage/sopticle/scrap/CrawlerComposite.java
- src/main/java/sopt/org/homepage/sopticle/scrap/LinkCrawler.java
- src/main/java/sopt/org/homepage/sopticle/scrap/LinkSource.java
- src/main/java/sopt/org/homepage/sopticle/scrap/WebDriverManager.java
- src/main/java/sopt/org/homepage/sopticle/scrap/crawler/BasicLinkCrawler.java
- src/main/java/sopt/org/homepage/sopticle/scrap/crawler/BehanceLinkCrawler.java
- src/main/java/sopt/org/homepage/sopticle/scrap/crawler/BrunchLinkCrawler.java
- src/main/java/sopt/org/homepage/sopticle/scrap/crawler/NaverLinkCrawler.java
- src/main/java/sopt/org/homepage/sopticle/scrap/crawler/VelogMainLinkCrawler.java
- src/main/java/sopt/org/homepage/sopticle/scrap/service/ScraperServiceImpl.java
- #37 
- 현재 솝티클 스크래핑 Selenium 활용 시, ChromeDriver 설정에 문제가 있어 오류 발생
- 솝티클을 더 많은 플랫폼에서 자동 스크래핑이 가능하도록 기능 개선
Composite 패턴을 활용하여
- 기본 플랫폼
- 비핸스
- 브런치
- 네이버
- 벨로그
크롤러를 등록 후, 입력받은 URL 을 파싱하여 플랫폼을 구분짓고 크롤링 작업 수행
도커환경에서 빌드될 때, Chrome Driver 세팅을 하도록 수정
Swagger 솝티클 업로드 API
> [Refac] 솝티클 스크래핑 기능 개선

- build.gradle
- src/main/java/sopt/org/homepage/scrap/WebDriverManager.java
- src/main/java/sopt/org/homepage/scrap/crawler/BasicLinkCrawler.java
- src/main/java/sopt/org/homepage/scrap/crawler/BrunchLinkCrawler.java
- src/main/java/sopt/org/homepage/scrap/crawler/NaverLinkCrawler.java
- src/main/java/sopt/org/homepage/scrap/crawler/VelogMainLinkCrawler.java
- #37 
Dev 환경에서 스크래핑이 안되는 오류가 있어 수정 진행
- Selenium 관련 패키지 버전 업그레이드
- JSoup 이중 인코딩으로 발생되는 이슈 수정
> [Fix] 스크래핑 오류 수정

- src/main/java/sopt/org/homepage/review/entity/ReviewEntity.java
> [FIX] Review 엔티티 제목, 설명 필드 varchar 길이 수정

- src/main/java/sopt/org/homepage/common/mapper/ResponseMapper.java
- src/main/java/sopt/org/homepage/internal/auth/AuthClient.java
- src/main/java/sopt/org/homepage/internal/playground/PlaygroundClient.java
- src/main/java/sopt/org/homepage/internal/playground/PlaygroundServiceImpl.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
---
labels: ''
assignees: ''
---
- closed #{이슈_번호}
> feat : 플그 api 호출 로직 수정

- .github/workflows/cd.develop.yml
- .github/workflows/cd.production.yml
---
labels: ''
assignees: ''
---
- closed #{이슈_번호}
> feat : 배포 스크립트에 ecr 이미지 삭제추가prod 스크립트 수정 

- .github/workflows/cd.develop.yml
- Testcontainers 대신 GitHub Actions services로 PostgreSQL 실행
- Docker-in-Docker 이슈 해결
- 테스트와 빌드 단계 분리 유지
---
labels: ''
assignees: ''
---
> infra :  GitHub Actions에서 PostgreSQL 서비스 컨테이너 사용

- .github/workflows/cd.develop.yml
---
labels: ''
assignees: ''
---
> infra : CI에서는 서비스 DB를 완전히 제거하고 Testcontainers에만 맡기도록 수정

- src/test/java/sopt/org/homepage/notification/service/IntegrationTestBase.java
- src/test/resources/application-test.yml
---
labels: ''
assignees: ''
---
> infra : 모든 테스트가 단일 PostgreSQL 컨테이너를 공유 하도록

- .github/workflows/cd.develop.yml
---
labels: ''
assignees: ''
---
> infra : CI 환경에서 환경 변수 제거

- .github/workflows/cd.develop.yml
- src/test/java/sopt/org/homepage/notification/service/IntegrationTestBase.java
- src/test/java/sopt/org/homepage/notification/service/command/NotificationCommandServiceTest.java
---
labels: ''
assignees: ''
---
> infra : Testcontainers만 사용 하도록 수정
